package dev.handspell.app.vision.classify

import dev.handspell.app.core.model.Letter
import dev.handspell.app.core.model.NormalizedHand
import java.io.InputStream
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.double
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the Kotlin forward pass to the numpy one.
 *
 * `training/testdata/mlp_golden.{bin,json}` are generated by `python -m handspell.mlp_golden` and
 * read here from the test resources directory the Gradle scaffold points at `training/testdata`.
 * Python's `tests/test_mlp_golden.py` asserts the same numbers from the other side and refuses to
 * pass if the fixture is stale, so a change to either implementation of the spec has to be a
 * deliberate, regenerated, two-language change — the same contract the normaliser golden enforces.
 *
 * 1e-5 absolute is the agreed tolerance: the weights are float32 in the file and both sides
 * accumulate in 64-bit, so real drift is orders of magnitude smaller and anything this test sees is
 * a genuine difference in the maths, not rounding.
 */
class MlpGoldenTest {

    private val tolerance = 1e-5

    private fun resource(name: String): InputStream =
        checkNotNull(javaClass.getResourceAsStream("/$name")) {
            "$name missing from test resources; run `python -m handspell.mlp_golden`"
        }

    private fun golden(): JsonDocument {
        val text = resource("mlp_golden.json").use { it.readBytes().decodeToString() }
        return JsonDocument(Json.parseToJsonElement(text).jsonObject)
    }

    private class JsonDocument(private val root: kotlinx.serialization.json.JsonObject) {
        val specVersion: Int get() = root.getValue("specVersion").jsonPrimitive.content.toInt()
        val inputDim: Int get() = root.getValue("inputDim").jsonPrimitive.content.toInt()
        val labels: List<String> get() = root.getValue("labels").jsonArray.map { it.jsonPrimitive.content }
        val cases: List<Case> get() = root.getValue("cases").jsonArray.map { element ->
            val case = element.jsonObject
            Case(
                name = case.getValue("name").jsonPrimitive.content,
                input = case.getValue("input").jsonArray.map { it.jsonPrimitive.double },
                expected = case.getValue("expected").jsonArray.map { it.jsonPrimitive.double },
            )
        }
    }

    private class Case(val name: String, val input: List<Double>, val expected: List<Double>)

    private fun classifier(): MlpLetterClassifier =
        MlpLetterClassifier.load({ resource("mlp_golden.bin") }, assetName = "mlp_golden.bin")

    @Test
    fun `the fixture matches this build's spec and dimensions`() {
        val document = golden()
        assertEquals(NormalizedHand.SPEC_VERSION, document.specVersion)
        assertEquals(NormalizedHand.VECTOR_DIM, document.inputDim)
        assertEquals(listOf("A", "B", "C", "D"), document.labels)
    }

    @Test
    fun `the forward pass reproduces the numpy probabilities`() {
        val classifier = classifier()
        val cases = golden().cases
        assertEquals(3, cases.size)

        for (case in cases) {
            val vector = FloatArray(case.input.size) { case.input[it].toFloat() }
            val probabilities = classifier.probabilities(vector)

            assertEquals("${case.name}: class count", case.expected.size, probabilities.size)
            for (index in case.expected.indices) {
                assertEquals(
                    "${case.name}: class $index",
                    case.expected[index],
                    probabilities[index],
                    tolerance,
                )
            }
        }
    }

    @Test
    fun `classify ranks the same winner the fixture does`() {
        val classifier = classifier()
        val labels = golden().labels

        for (case in golden().cases) {
            val vector = FloatArray(case.input.size) { case.input[it].toFloat() }
            val result = classifier.classify(NormalizedHand(vector), timestampMs = 42L)

            val winner = Letter.valueOf(labels[case.expected.indices.maxBy { case.expected[it] }])
            assertEquals(case.name, winner, result.top?.letter)
            assertEquals(case.name, 42L, result.timestampMs)
            assertEquals(
                case.name,
                case.expected.max(),
                result.top!!.probability.toDouble(),
                tolerance,
            )
            assertEquals(1.0, result.ranked.sumOf { it.probability.toDouble() }, 1e-5)
            assertEquals(result.ranked, result.ranked.sortedByDescending { it.probability })
        }
    }

    @Test
    fun `the mlp reports no exemplar distance`() {
        val classifier = classifier()
        val vector = FloatArray(NormalizedHand.VECTOR_DIM)
        assertTrue(classifier.classify(NormalizedHand(vector), 0L).nearestDistance.isNaN())
    }

    @Test
    fun `supported letters come from the labels in class-index order`() {
        val classifier = classifier()
        assertEquals(listOf(Letter.A, Letter.B, Letter.C, Letter.D), classifier.supportedLetters)
        assertEquals("mlp-v1", classifier.modelId)
        assertEquals(NormalizedHand.SPEC_VERSION, classifier.specVersion)
    }

    @Test
    fun `probabilities rejects a vector of the wrong width`() {
        val classifier = classifier()
        val error = org.junit.Assert.assertThrows(IllegalArgumentException::class.java) {
            classifier.probabilities(FloatArray(10))
        }
        assertTrue(error.message!!.contains("expected"))
    }
}
