"""Generates training/testdata/mlp_golden.{bin,json}: a tiny fixed-seed HSML
model plus three inputs and their expected softmax outputs, so the Kotlin
forward pass in MlpLetterClassifier.kt is pinned to the numpy one in
handspell.hsml.

This is the same trick as handspell.golden does for the normaliser, for the
same reason: the two implementations of a shared spec drift silently
otherwise, and the drift only shows up as a letter that scores slightly wrong
on a phone. The net here is deliberately absurd -- 66 -> 8 -> 4 -> 4 with
random weights and letters A..D as labels -- because its job is to exercise
every field of the container and every branch of the forward pass, not to
recognise anything.

Numbers in the JSON are written with 9 significant digits and the expected
outputs are computed *after* that rounding, so the Kotlin reader and this
generator start from bit-identical inputs.

Run as `python -m handspell.mlp_golden` to regenerate both files.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from handspell.hsml import Activation, Layer, Model, forward, pack
from handspell.normalize import SPEC_VERSION, VECTOR_DIM

_TESTDATA = Path(__file__).resolve().parent.parent / "testdata"
_BIN_PATH = _TESTDATA / "mlp_golden.bin"
_JSON_PATH = _TESTDATA / "mlp_golden.json"

_SEED = 20260913
_HIDDEN_DIMS = (8, 4)
_LABELS = ["A", "B", "C", "D"]
_CASE_COUNT = 3
_WEIGHT_GAIN = 3.0


def _round9(value: float) -> float:
    """9 significant digits, with 0.0 written as 0.0 rather than -0."""
    if value == 0.0:
        return 0.0
    return float(f"{float(value):.9g}")


def build_model() -> Model:
    """The fixed-seed net. Weights are scaled by _WEIGHT_GAIN/sqrt(fan_in): big
    enough that the softmax is clearly peaked (a fixture where every class sits
    at 0.25 would pass even if the reader dropped a layer), small enough that
    the logits stay in single digits."""
    rng = np.random.default_rng(_SEED)
    dims = [VECTOR_DIM, *_HIDDEN_DIMS, len(_LABELS)]
    layers: list[Layer] = []
    for index in range(len(dims) - 1):
        in_dim, out_dim = dims[index], dims[index + 1]
        scale = _WEIGHT_GAIN / np.sqrt(in_dim)
        weights = (rng.normal(scale=scale, size=(out_dim, in_dim))).astype(np.float32)
        bias = (rng.normal(scale=0.1, size=out_dim)).astype(np.float32)
        is_last = index == len(dims) - 2
        layers.append(
            Layer(
                weights=weights,
                bias=bias,
                activation=Activation.IDENTITY if is_last else Activation.RELU,
            )
        )
    return Model(layers=layers, labels=list(_LABELS))


def build_inputs() -> np.ndarray:
    """Three inputs shaped like normalised hands: a shape block around unit
    scale and a unit-ish orientation block, then rounded to what the JSON can
    actually carry."""
    rng = np.random.default_rng(_SEED + 1)
    inputs = np.empty((_CASE_COUNT, VECTOR_DIM), dtype=np.float64)
    for case in range(_CASE_COUNT):
        shape = rng.normal(scale=0.6, size=60)
        orientation = rng.normal(size=6)
        orientation[:3] /= np.linalg.norm(orientation[:3])
        orientation[3:] /= np.linalg.norm(orientation[3:])
        vector = np.concatenate([shape, orientation])
        inputs[case] = [_round9(value) for value in vector]
    return inputs


def golden_bytes() -> bytes:
    model = build_model()
    return pack(model.layers, model.labels)


def golden_json_text() -> str:
    model = build_model()
    inputs = build_inputs()
    probabilities = forward(model, inputs)
    document = {
        "description": (
            "Fixed-seed HSML model and its expected softmax outputs. Generated by "
            "`python -m handspell.mlp_golden`; read by tests/test_mlp_golden.py and "
            "MlpGoldenTest.kt, which must agree to 1e-5."
        ),
        "specVersion": SPEC_VERSION,
        "inputDim": VECTOR_DIM,
        "labels": list(model.labels),
        "layers": [
            {"inDim": layer.in_dim, "outDim": layer.out_dim, "activation": layer.activation.name.lower()}
            for layer in model.layers
        ],
        "cases": [
            {
                "name": f"case_{index}",
                "input": [_round9(value) for value in inputs[index]],
                "expected": [_round9(value) for value in probabilities[index]],
            }
            for index in range(_CASE_COUNT)
        ],
    }
    return json.dumps(document, indent=2) + "\n"


def main() -> None:
    _TESTDATA.mkdir(parents=True, exist_ok=True)
    _BIN_PATH.write_bytes(golden_bytes())
    _JSON_PATH.write_text(golden_json_text(), encoding="utf-8")
    print(f"Wrote {_BIN_PATH} and {_JSON_PATH}")


if __name__ == "__main__":
    main()
