#!/usr/bin/env python3
"""Generates the alphabet menu's hand wireframes from the classifier's reference exemplars.

Usage: scripts/gen-web-wireframes.py [path/to/handshapes.js]   (default: web/src/js/handshapes.js)

The native reference guide (CanonicalHandshapeCatalog) uses the first stage-1 exemplar per letter, so this does
too; both stay the same picture. J and Z use I and D as starting poses, respectively, with authored fingertip
paths. These guides describe motion; they are not extra static classifier exemplars.
"""
import csv, json, sys, pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
CSV = REPO / "android/app/src/main/assets/classifier/references-v1.csv"
OUT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else REPO / "web/src/js/handshapes.js")
MOTION = {"J", "Z"}
# MediaPipe hand connections (same as HandLandmarker.HAND_CONNECTIONS).
CONNECTIONS = [(0,1),(1,2),(2,3),(3,4),(0,5),(5,6),(6,7),(7,8),(5,9),(9,10),(10,11),(11,12),
               (9,13),(13,14),(14,15),(15,16),(13,17),(17,18),(18,19),(19,20),(0,17)]
BOX, PAD = 64.0, 0.16

def wireframe(values):
    e1, e3 = values[60:63], values[63:66]
    e2 = (e3[1]*e1[2]-e3[2]*e1[1], e3[2]*e1[0]-e3[0]*e1[2], e3[0]*e1[1]-e3[1]*e1[0])
    # Restore display orientation instead of making G/Q and K/P look identical.
    pts = [(0.0, 0.0)] + [
        tuple(values[i*3]*e1[a] + values[i*3+1]*e2[a] + values[i*3+2]*e3[a] for a in range(2))
        for i in range(20)
    ]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    rx, ry = max(max(xs) - min(xs), 1e-4), max(max(ys) - min(ys), 1e-4)
    usable = BOX * (1 - 2 * PAD)
    scale = min(usable / rx, usable / ry)
    ox, oy = (BOX - rx * scale) / 2, (BOX - ry * scale) / 2
    mapped = [((x - min(xs)) * scale + ox, (y - min(ys)) * scale + oy) for x, y in pts]
    d = "".join(f"M{mapped[a][0]:.1f} {mapped[a][1]:.1f}L{mapped[b][0]:.1f} {mapped[b][1]:.1f}" for a, b in CONNECTIONS)
    return {"d": d, "dots": [[round(x, 1), round(y, 1)] for x, y in mapped]}

shapes = {}
with open(CSV) as f:
    rows = csv.reader(line for line in f if not line.startswith("#"))
    next(rows)  # header
    for row in rows:
        letter = row[0]
        if letter in MOTION or letter in shapes or len(row) != 67:
            continue
        shapes[letter] = wireframe([float(v) for v in row[1:]])

# Fit the starting hand beneath its active fingertip so the entire tracing stays in the tile.
for letter, base, tip, origin, motion, arrow in [
    ("J", "I", 20, (43, 8), "M0 0L0 25Q0 35 -10 35Q-17 35 -17 27", "M23 38L26 35L29 38"),
    ("Z", "D", 8, (13, 8), "M0 0L34 0L0 24L34 24", "M42 28L47 32L42 36"),
]:
    pose = shapes[base]
    x, y = pose["dots"][tip]
    shapes[letter] = {
        **pose,
        "motion": motion,
        "transform": f"translate({origin[0] - x * 0.42:.2f} {origin[1] - y * 0.42:.2f}) scale(0.42)",
        "origin": list(origin),
        "arrow": arrow,
    }

OUT.write_text(
    "// Generated by scripts/gen-web-wireframes.py from references-v1.csv. Do not edit by hand.\n"
    f"export const wireframes = {json.dumps(shapes, separators=(',', ':'))};\n"
)
print(f"wrote {OUT} with letters: {' '.join(sorted(shapes))}")
